// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback keeps `prisma generate` working on Vercel where DATABASE_URL is not set.
    // The actual runtime connection is configured in lib/db.ts via TURSO_DATABASE_URL.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
